variable "private_endpoint_name" {
  description = "Specifies the Name of the Private Endpoint."
  type        = string
}

variable "location" {
  description = "Azure location."
  type        = string
}

variable "resource_group_name" {
  description = "Resource group name."
  type        = string
}

variable "custom_private_endpoint_nic_name" {
  description = "Custom network interface name of the Private endpoint, generated by Azure if not set."
  type        = string
  default     = null
}

variable "subnet_id" {
  description = "ID of the subnet in which the Private Endpoint will be created."
  type        = string
}

variable "ip_configurations" {
  description = <<EOD
List of IP Configuration object. Any modification to the parameters of the IP Configuration object forces a new resource to be created.
```
name               = Name of the IP Configuration.
member_name        = Member name of the IP Configuration. If it is not specified, it will use the value of `subresource_name`. Only valid if `target_resource` is not a Private Link Service.
subresource_name   = Subresource name of the IP Configuration. Only valid if `target_resource` is not a Private Link Service.
private_ip_address = Private IP address within the Subnet of the Private Endpoint.
```
EOD
  type = list(object({
    name               = optional(string, "default")
    member_name        = optional(string)
    subresource_name   = optional(string)
    private_ip_address = string
  }))
  default  = []
  nullable = true
}

variable "private_dns_zone_group_name" {
  description = "Specifies the Name of the Private DNS Zone Group"
  type        = string
}

variable "custom_private_dns_zone_group_name" {
  type        = string
  description = "Custom Private DNS Zone Group name, generated if not set."
  default     = ""
}

variable "custom_private_service_connection_name" {
  type        = string
  description = "Custom Private Service Connection name, generated if not set."
  default     = ""
}

variable "is_manual_connection" {
  description = "Does the Private Endpoint require manual approval from the remote resource owner? Default to `false`."
  type        = bool
  default     = false
}

variable "request_message" {
  description = "A message passed to the owner of the remote resource when the Private Endpoint attempts to establish the connection to the remote resource. Only valid if `is_manual_connection` is set to `true`."
  type        = string
  default     = "Private Endpoint Deployment"
}

variable "target_resource" {
  description = "Private Link Service Alias or ID of the target resource."
  type        = string
}

variable "subresource_name" {
  description = "A list of subresource names which the Private Endpoint is able to connect to."
  type        = list(string)
  default     = []
}

# variable "use_existing_private_dns_zones" {
#   description = "Boolean to create the Private DNS Zones corresponding to the Private Endpoint. If you wish to centralize the Private DNS Zones in another Resource Group that could belong to another subscription, set this option to `true` and use the `private-dns-zone` submodule directly."
#   type        = bool
#   default     = false
# }

variable "private_dns_zones_ids" {
  description = "IDs of the Private DNS Zones in which a new record will be created for the Private Endpoint. One of `private_dns_zones_ids` or `private_dns_zones_names` must be specified."
  type        = list(string)
  default     = []
}

variable "private_dns_zones_names" {
  description = "Names of the Private DNS Zones to create. One of `private_dns_zones_ids` or `private_dns_zones_names` must be specified."
  type        = list(string)
  default     = []
}

variable "private_dns_zones_vnets_ids" {
  description = "IDs of the VNets to link to the Private DNS Zones."
  type        = list(string)
  default     = []
}

variable "private_service_connection_name" {
  description = "Specifies the Name of the Private Service Connection. Changing this forces a new resource to be created."
  type        = string
}

# variable "resource_id" {
#   description = "The ID of the Private Link Enabled Remote Resource which this Private Endpoint should be connected to. One of private_connection_resource_id or private_connection_resource_alias must be specified."
#   type = string
#   default = null
# }

# variable "resource_alias" {
#   description = "The Service Alias of the Private Link Enabled Remote Resource which this Private Endpoint should be connected to. One of private_connection_resource_id or private_connection_resource_alias must be specified."
#   type = string
#   default = null
# }
